#!/usr/bin/env python3
"""Site invariants that are easy to break silently and hard to notice.

Run it with no arguments; it exits 1 and prints every violation it found.

WHY THIS EXISTS
---------------
Each check below corresponds to something that actually went wrong in this
repository, not to a hypothetical. The healthcare landing pages spent several
deploys on `style-src 'self' 'unsafe-inline'` while every other page ran
`style-src 'self'`, because they were hand-written rather than generated by
build.py and nothing compared them. A measurement ID was once changed in the
sources but not in the generated output, leaving five pages pointing at a dead
property. Both are invisible in a diff and invisible in the browser.

A NOTE ON THE CSP REGEX
-----------------------
The obvious pattern, content=["']([^"']+)["'], is wrong and silently so: a CSP
contains 'self' in single quotes, so the character class stops at the first one
and every page compares equal as the string "default-src ". A check that cannot
fail is worse than no check, because it is reassuring. Capture the opening
quote and require the same quote to close.
"""

import glob
import io
import os
import re
import sys

CSP_RX = re.compile(
    r'<meta[^>]*?http-equiv=["\']Content-Security-Policy["\'][^>]*?content=(["\'])(.*?)\1',
    re.I | re.S,
)
GA_ID_RX = re.compile(r"G-[A-Z0-9]{8,}")

failures = []


def fail(msg):
    failures.append(msg)


def read(path):
    return io.open(path, encoding="utf-8").read()


def pages():
    found = set()
    for pat in ("*.html", "*/index.html", "*/*/index.html", "*/*/*/index.html"):
        found.update(glob.glob(pat))
    return sorted(p for p in found if not p.startswith("src/"))


def parse_csp(text):
    """CSP string -> {directive: set(sources)}. Returns None when absent."""
    m = CSP_RX.search(text)
    if not m:
        return None
    out = {}
    for part in m.group(2).split(";"):
        bits = part.split()
        if bits:
            out[bits[0]] = set(bits[1:])
    return out


def check_csp_present_and_consistent(all_pages):
    for p in all_pages:
        if parse_csp(read(p)) is None:
            fail(f"{p}: no Content-Security-Policy meta tag")


def check_no_inline_styles_under_strict_csp(all_pages):
    """A page promising style-src 'self' must not rely on inline CSS.

    Catches the drift in both directions: a page that quietly regains an inline
    <style> block (its own policy would then block it, so the page renders
    unstyled), and a page that quietly relaxes to 'unsafe-inline' to keep one.
    """
    # 404.html is the one documented exception, and the reason is in _headers:
    # it renders at any missing URL, so it carries its CSS inline to cost exactly
    # one request no matter which URL produced it. Listing it here rather than
    # skipping it silently means removing the exception is a deliberate edit.
    INLINE_CSS_ALLOWED = {"404.html"}

    for p in all_pages:
        s = read(p)
        csp = parse_csp(s)
        if not csp:
            continue
        style_src = csp.get("style-src", csp.get("default-src", set()))
        strict = "'unsafe-inline'" not in style_src
        has_block = "<style" in s
        inline_attrs = len(re.findall(r"<\w+[^>]*? style=", s))

        if strict and (has_block or inline_attrs):
            what = []
            if has_block:
                what.append("a <style> block")
            if inline_attrs:
                what.append(f"{inline_attrs} inline style= attribute(s)")
            fail(
                f"{p}: CSP declares style-src without 'unsafe-inline' but the page contains "
                + " and ".join(what)
                + " — the browser refuses them and the page renders unstyled"
            )
        if not strict and p not in INLINE_CSS_ALLOWED:
            fail(
                f"{p}: CSP allows style-src 'unsafe-inline'. Every other content page runs "
                f"style-src 'self'; move the CSS into a same-origin file rather than leaving "
                f"this page weaker than the rest of the site."
            )


def check_analytics_consistent(all_pages):
    """Every page that boots analytics must load the tag, with one shared ID."""
    ids = set()
    for p in all_pages:
        s = read(p)
        boots = re.search(r'src=["\'][^"\']*analytics\.js', s) is not None
        tag = "googletagmanager.com/gtag/js" in s
        page_ids = set(GA_ID_RX.findall(s))
        ids |= page_ids
        if boots and not tag:
            fail(f"{p}: loads analytics.js but never loads gtag.js — the config queues and is never drained")
        if tag and not boots:
            fail(f"{p}: loads gtag.js but not analytics.js — the tag loads and is never configured")
        if boots and len(page_ids) > 1:
            fail(f"{p}: more than one measurement ID on one page: {sorted(page_ids)}")
        if boots and tag:
            csp = parse_csp(s) or {}
            script = csp.get("script-src", csp.get("default-src", set()))
            connect = csp.get("connect-src", csp.get("default-src", set()))
            img = csp.get("img-src", csp.get("default-src", set()))
            if "https://www.googletagmanager.com" not in script:
                fail(f"{p}: loads gtag.js but script-src does not allow googletagmanager.com")
            if not any("google-analytics.com" in x for x in connect):
                fail(f"{p}: connect-src does not allow google-analytics.com — hits are refused, silently")
            if not any("google-analytics.com" in x for x in img):
                fail(f"{p}: img-src does not allow google-analytics.com — the image-beacon fallback is refused")

    # Generated output is the usual place a stale ID survives an edit.
    for extra in ("analytics.js",):
        if os.path.exists(extra):
            ids |= set(GA_ID_RX.findall(read(extra)))
    if len(ids) > 1:
        fail(f"more than one GA measurement ID in the repository: {sorted(ids)} — generated files are probably stale")


def check_internal_links(all_pages):
    for p in all_pages:
        base = os.path.dirname(p)
        for _attr, val in re.findall(r'(href|src)=["\']([^"\']+)["\']', read(p)):
            if val.startswith(("http://", "https://", "mailto:", "tel:", "#", "data:", "javascript:")):
                continue
            target = val.split("#")[0].split("?")[0]
            if not target:
                continue
            path = target[1:] if target.startswith("/") else os.path.normpath(os.path.join(base, target))
            if not any(os.path.exists(c) for c in (path, os.path.join(path, "index.html"))):
                fail(f"{p}: broken internal link -> {val}")


def check_sitemap(all_pages):
    if not os.path.exists("sitemap.xml"):
        fail("sitemap.xml missing")
        return
    locs = re.findall(r"<loc>https://cindrasec\.com/([^<]*)</loc>", read("sitemap.xml"))
    for l in locs:
        f = (l + "index.html") if (l == "" or l.endswith("/")) else l
        if not os.path.exists(f):
            fail(f"sitemap.xml lists /{l} but {f} does not exist")
    listed = {"/" + l for l in locs}
    for p in all_pages:
        if "404" in p:
            continue
        s = read(p)
        if re.search(r'<meta[^>]*name=["\']robots["\'][^>]*noindex', s, re.I):
            continue
        url = "/" + (p[: -len("index.html")] if p.endswith("index.html") else p)
        if url not in listed:
            fail(f"{url} is indexable but is not in sitemap.xml")


def check_service_worker():
    if not os.path.exists("sw.js"):
        return
    for asset in re.findall(r"SCOPE \+ '([^']+)'", read("sw.js")):
        if not os.path.exists(asset):
            fail(f"sw.js precaches {asset}, which does not exist — install() rejects and the worker never activates")


def main():
    if not os.path.exists("index.html"):
        print("run this from the repository root", file=sys.stderr)
        return 2
    all_pages = pages()
    check_csp_present_and_consistent(all_pages)
    check_no_inline_styles_under_strict_csp(all_pages)
    check_analytics_consistent(all_pages)
    check_internal_links(all_pages)
    check_sitemap(all_pages)
    check_service_worker()

    if failures:
        print(f"{len(failures)} problem(s) found across {len(all_pages)} pages:\n")
        for f in failures:
            print(f"  - {f}")
        return 1
    print(f"all site invariants hold across {len(all_pages)} pages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
